name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install build tools
      run: |
        sudo apt install -y subversion g++ zlib1g-dev build-essential git python python3 libncurses5-dev gawk gettext unzip file libssl-dev wget libelf-dev ecj fastjar java-propose-classpath build-essential libncursesw5-dev python unzip   
    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
